#!/bin/bash

# Some Variables

AppName="SteamDeck-Tweak"
AppVersion="0.0.1"
AppNameTitle="${AppName}  -  ${AppVersion}"

msgBoxText="null"

###############################################################################
## Steamos ReadOnly Menu
###############################################################################
_steamos-readonly(){
    MainMenuBox=$(zenity --list \
                        --title="${AppNameTitle}" \
                        --height=320 \
                        --width=640 \
                        --ok-label="Ok" \
                        --cancel-label="Cancel" \
                        --text="SteamOS partition It's read only enabled by default. \nWhat do you want to do?" \
                        --radiolist \
                        --column="" \
                        --column="steamos-readonly:" \
                        --column="Description:" \
                        1 "Disable" "You can make changes in SteamOS with this" \
                        2 "Enable" "Protect SteamOS Partition again" \
                        3 "Status" "Check status about Partition state" )

    ans=$?
    if [ $ans -eq 0 ]
    then
        echo "Has elegido: ${MainMenuBox}"
            if [ ${MainMenuBox} == "Disable" ]; then
                    echo "sudo steamos-readonly disable"
                    msgBoxText="steamos-readonly disabled!"
                    _msgBox
                    _mainMenu
            elif [ ${MainMenuBox} == "Enable" ]; then
                    echo "sudo steamos-readonly enable"
                    msgBoxText="steamos-readonly enabled!"
                    _msgBox
                    _mainMenu
            else
                echo "Nothing"
            fi
    else
        echo "No has elegido ningún componente"
        _mainMenu
    fi
}


_msgBox(){
    zenity --info \
            --title="${AppNameTitle}" \
            --width=250 \
            --text="${msgBoxText}"
}

###############################################################################
## Menu Comprobacion
###############################################################################
_checkMenu(){
    if [ ${MainMenuBox} == "steamos-readonly" ]
        then
            echo "Go Menu steamos-readonly"
            _steamos-readonly
        else
            echo "go Main Menu"
            _mainMenu
    fi
}

###############################################################################
## Menu Principal
###############################################################################
_mainMenu(){
    MainMenuBox=$(zenity --list \
                        --title="${AppNameTitle}" \
                        --height=320 \
                        --width=640 \
                        --ok-label="Ok" \
                        --cancel-label="Cancel" \
                        --text="" \
                        --radiolist \
                        --column="" \
                        --column="Select:" \
                        --column="Description:" \
                        1 "steamos-readonly" "Enable or Disable Steam Deck Partition Read Only mode." \
                        2 "language" "Change Steam Deck language." \
                        3 "SSH" "Install SSH server in Steam Deck." \
                        4 "AUR" "Install AUR Package Manager." \
                        5 "lutris" "Install Lutris Game Manager (Usefull for Non-Steam Games)" \
                        6 "protonup-qt" "Proton GE Installer (Recomended for non compatible Steam Deck Games)")

    ans=$?
    if [ $ans -eq 0 ]
    then
        echo "Has elegido: ${MainMenuBox}"
        _checkMenu
    else
        echo "Has Salido del sistema"
        exit
    fi
}

# Launch Program
_mainMenu